// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20251119040114_AddAuditFields")]
    partial class AddAuditFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Sql.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Industry")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 19, 4, 1, 14, 210, DateTimeKind.Utc).AddTicks(6314),
                            Description = "Leading technology company specializing in software development",
                            Industry = "Technology",
                            Name = "Tech Corp",
                            Website = "https://techcorp.example.com"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 19, 4, 1, 14, 210, DateTimeKind.Utc).AddTicks(6317),
                            Description = "Premier financial services provider",
                            Industry = "Finance",
                            Name = "Finance Solutions Ltd",
                            Website = "https://financesolutions.example.com"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 19, 4, 1, 14, 210, DateTimeKind.Utc).AddTicks(6320),
                            Description = "Healthcare technology innovator",
                            Industry = "Healthcare",
                            Name = "Health Plus",
                            Website = "https://healthplus.example.com"
                        });
                });

            modelBuilder.Entity("Backend.Models.Sql.JobPosting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Full-time");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PostedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PostedDate");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("JobPostings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 19, 4, 1, 14, 210, DateTimeKind.Utc).AddTicks(6491),
                            Description = "We are seeking an experienced .NET developer to join our team...",
                            EmploymentType = "Full-time",
                            Location = "Ho Chi Minh City",
                            PostedDate = new DateTime(2025, 11, 19, 4, 1, 14, 210, DateTimeKind.Utc).AddTicks(6488),
                            Requirements = "5+ years of experience with .NET Core, C#, SQL Server, and Azure",
                            SalaryMax = 3500m,
                            SalaryMin = 2000m,
                            Status = "Open",
                            Title = "Senior .NET Developer"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 19, 4, 1, 14, 210, DateTimeKind.Utc).AddTicks(6497),
                            Description = "Join our dynamic team as a Frontend Developer...",
                            EmploymentType = "Full-time",
                            Location = "Hanoi",
                            PostedDate = new DateTime(2025, 11, 19, 4, 1, 14, 210, DateTimeKind.Utc).AddTicks(6496),
                            Requirements = "3+ years of experience with React, TypeScript, and modern frontend tools",
                            SalaryMax = 2500m,
                            SalaryMin = 1500m,
                            Status = "Open",
                            Title = "Frontend React Developer"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 11, 19, 4, 1, 14, 210, DateTimeKind.Utc).AddTicks(6501),
                            Description = "Seeking a detail-oriented Financial Analyst...",
                            EmploymentType = "Full-time",
                            Location = "Da Nang",
                            PostedDate = new DateTime(2025, 11, 19, 4, 1, 14, 210, DateTimeKind.Utc).AddTicks(6500),
                            Requirements = "Bachelor's degree in Finance, 2+ years experience in financial analysis",
                            SalaryMax = 2000m,
                            SalaryMin = 1200m,
                            Status = "Open",
                            Title = "Financial Analyst"
                        });
                });

            modelBuilder.Entity("Backend.Models.Sql.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Candidate");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 0,
                            CreatedAt = new DateTime(2025, 11, 19, 4, 1, 14, 210, DateTimeKind.Utc).AddTicks(6526),
                            Email = "admin@recruitment.com",
                            FullName = "admin",
                            IsActive = true,
                            PasswordHash = "AQAAAAEAACcQAAAAEHashed_Password_Here",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 0,
                            CreatedAt = new DateTime(2025, 11, 19, 4, 1, 14, 210, DateTimeKind.Utc).AddTicks(6529),
                            Email = "hr@recruitment.com",
                            FullName = "hr_manager",
                            IsActive = true,
                            PasswordHash = "AQAAAAEAACcQAAAAEHashed_Password_Here",
                            Role = "HR"
                        });
                });

            modelBuilder.Entity("Backend.Models.Sql.JobPosting", b =>
                {
                    b.HasOne("Backend.Models.Sql.Company", "Company")
                        .WithMany("JobPostings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Sql.User", null)
                        .WithMany("JobPostings")
                        .HasForeignKey("UserId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Backend.Models.Sql.User", b =>
                {
                    b.HasOne("Backend.Models.Sql.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Backend.Models.Sql.Company", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("Backend.Models.Sql.User", b =>
                {
                    b.Navigation("JobPostings");
                });
#pragma warning restore 612, 618
        }
    }
}
